[project]
name = "navboard"
version = "1.0.0"
description = "NavBoard - 内外网服务导航管理平台。"
readme = "README.md"
maintainers = [{name = "ywang_wnlo", email = "ywang_wnlo@qq.com"}]
dependencies = [
    "flask",
]
