-- 初始化数据库
-- 删除已有数据并创建空表

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS gmap;
DROP TABLE IF EXISTS nav_entry;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE gmap (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  k TEXT UNIQUE NOT NULL,
  v TEXT NOT NULL
);

CREATE TABLE nav_entry (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  local_ip TEXT,
  port INTEGER,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
